const PROJECTS = [
    {
        title:     "Knowverse",
        dimension: "game",
        genres:    ["TRIVIA RPG", "EXPLORATION", "EDUCATIONAL"],
        platform:  "Android",
        date:      "Jan 2026 – Apr 2026",
        dateSort:  "2026-04",
        roles:     ["Technical Lead", "Game Designer"],
        desc:      "A mobile trivia RPG set inside a virtual library where players explore themed rooms, battle Book Monsters through knowledge-based challenges, and uncover rewards that encourage curiosity and discovery.",
        image:     "projects/games/knowverse/Knowverse_Thumbnail.png",
        status:    "mvp",
        playable:  true,
        links:     { detail: "knowverse.html" }
    },
    {
        title:     "ElfaBad",
        dimension: "game",
        genres:    ["ARCADE", "ACTION", "TYPING ROGUELITE"],
        platform:  "PC",
        date:      "Jan 2025 – Apr 2025",
        dateSort:  "2025-04",
        roles:     ["Technical Lead", "Game Designer"],
        desc:      "A frantic arcade survival game where movement is controlled through randomized keyboard letters. Dodge hazards, adapt to shifting controls, and outrun the relentless Lexicon deep within an ever-changing dungeon.",
        image:     "projects/games/elfabad/ElfaBad_Thumbnail.png",
        status:    "mvp",
        links:     { detail: "elfabad.html" }
    },
    {
        title:     "Libra",
        dimension: "game",
        genres:    ["SYMMETRY PUZZLE"],
        platform:  "PC",
        date:      "Sep 2024 – Apr 2025",
        dateSort:  "2025-04",
        roles:     ["Product Manager", "Design Lead"],
        desc:      "A relaxing puzzle game where players restore cosmic balance through satisfying symmetry challenges.",
        image:     "projects/games/libra/Libra_Thumbnail.png",
        status:    "mvp",
        links:     { detail: "libra.html" }
    },
    {
        title:     "Ace",
        dimension: "game",
        genres:    ["ACTION", "PLATFORMER"],
        platform:  "PC",
        date:      "Jan 2024 – Apr 2024",
        dateSort:  "2024-04",
        roles:     ["Technical Lead", "Game Designer"],
        desc:      "A fast-paced dungeon platformer where players use throwable boomerang cards to chain attacks, dodge hazards, and clear enemy-filled combat rooms.",
        image:     "projects/games/ace/Ace_Thumbnail.png",
        status:    "mvp",
        links:     { detail: "ace.html" }
    },
    {
        title:     "ServeEM",
        dimension: "personal",
        genres:    ["ARCADE"],
        platform:  "Android",
        date:      "Dec 2020 – Jan 2021",
        dateSort:  "2021-01",
        roles:     ["Solo Developer"],
        desc:      "Serve a super hungry cat its burgers! My first solo Unity2D mobile game.",
        image:     "projects/games/serveem/ServeEM_Thumbnail.png",
        status:    "mvp",
        playable:  true,
        links:     { detail: "serveem.html", playstore: "#" }
    },
    {
        title:     "Bon-Tress",
        dimension: "game",
        genres:    ["TOWER DEFENSE", "STRATEGY"],
        platform:  "PC",
        date:      "Jan 2020 – Sep 2020",
        dateSort:  "2020-09",
        roles:     ["Multi-Disciplinary"],
        desc:      "A pedagogical tower defense game that transforms study habits and learning strategies into gameplay mechanics, tasking players with defending the academy through strategic planning and resource management.",
        image:     "projects/games/bontress/Bon-Tress_Thumbnail.png",
        status:    "mvp",
        playable:  true,
        links:     { detail: "bontress.html" }
    },
    {
        title:     "Interaction Analysis - Ib (Open PDF)",
        dimension: "analysis",
        date:      "2023",
        dateSort:  "2023-11-24",
        desc:      "An analysis of Ib focusing on environmental storytelling, player interaction design, and the psychological techniques used to create tension, uncertainty, and emotional immersion.",
        image:     "projects/gameanalysis/ib/ibanalysisthumbnail.png",
        links:     { pdf: "projects/gameanalysis/ib/Game_Analysis-Ib.pdf" }
    },
    {
        title:     "Scene Analysis - Undertale (Open PDF)",
        dimension: "analysis",
        date:      "2023",
        dateSort:  "2023-10-27",
        desc:      "A scene analysis of Undertale's Last Corridor, examining how dialogue, pacing, player consequence, and atmosphere build one of the game's most emotionally powerful confrontations.",
        image:     "projects/gameanalysis/undertale/undertaleanalysisthumbnail.png",
        links:     { pdf: "projects/gameanalysis/undertale/Game_Analysis-Undertale.pdf" }
    },
    {
        title:     "Level Design - Kurohebi's Lost Archive",
        dimension: "leveldesign",
        date:      "2024",
        dateSort:  "2024-00",
        desc:      "A level design document for Kurohebi's Lost Archive, detailing spatial flow, encounter pacing, and environmental storytelling.",
        image:     "projects/leveldesign/LevelDesign-Kurohebi",
        imageType: "pdf",
        links:     { pdf: "projects/leveldesign/LevelDesign-Kurohebi.pdf" }
    },
    {
        title:     "Level Design - MegaManMaker",
        dimension: "leveldesign",
        date:      "2024",
        dateSort:  "2024-01",
        desc:      "A level design document for a MegaMan Maker stage, focusing on obstacle composition, rhythm, and difficulty curve.",
        image:     "projects/leveldesign/LevelDesign-MegaManMaker",
        imageType: "pdf",
        links:     { pdf: "projects/leveldesign/LevelDesign-MegaManMaker.pdf" }
    },
];
